name: Observe PDF

on:
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch:

jobs:
  observe:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: "18"
        cache: 'npm'
    - name: Cache nodd_modules
      uses: actions/cache@v3
      id: node_modules_cache_id
      env:
        cache-name: cache-node-modules
      with:
        path: "**/node_modules"
        key: ${{ runner.os }}-npm-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
    - name: Install npm modules if needed
      if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
      run: npm install
    - name: Run script
      run: npm run start
    - name: Push commit
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git branch issue
        git checkout issue
        git add .
        git commit -m "chore: add diff"
        git push origin issue
    - name: Create PR
      if: ${{ steps.check_pr.outputs.count == 0 }}
      run: gh pr create -B main -t 'PR タイトル' -b '内容'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}