name: Observe PDF

on:
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch:

jobs:
  observe:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: 'npm'

      - name: Cache node_modules
        uses: actions/cache@v3
        id: node_modules_cache_id
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-npm-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install npm modules if needed
        if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
        run: npm install

      - name: Decode dotenv file
        run: |
          echo "${{ secrets.DOT_ENV_BASE64 }}" > .env-base64.txt
          base64 --decode .env-base64.txt > .env
          rm .env-base64.txt

      - name: Run script
        run: npm run start

      - name: Setup date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        env:
          TZ: 'Asia/Tokyo'

      - name: Check diff
        id: diff
        run: | 
          git add -N .
          git diff --name-only --exit-code
        continue-on-error: true

      - name: Check PR
        id: check_pr
        run: echo "count=$(gh pr list -B main -H ${{ github.ref_name }} --json 'id' -q '.[] | length')" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push commit and create PR if needed
        if: ${{ steps.diff.outcome == 'failure' && steps.check_pr.outputs.count == '' }}
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git branch ${{ steps.date.outputs.date }}
          git checkout ${{ steps.date.outputs.date }}
          git add .
          git commit -m "chore: [bot] 画像の差分を追加"
          git push origin ${{ steps.date.outputs.date }}
          gh pr create -B main -t '${{ steps.date.outputs.date }} 画像に差分が発生' -b ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}